# Generated by Django 5.0.6 on 2024-05-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sticky_notes_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="mobile_number",
        ),
        migrations.AddField(
            model_name="author",
            name="username",
            field=models.CharField(default="default_username", max_length=30),
            preserve_default=False,
        ),
    ]
